# Site settings
title: Suker的记录 
email: imsuker@qq.com
description: > 
  记录平常遇到的一些问题。
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://imsuker.github.io" # the base hostname & protocol for your site
github_username: imsuker 

# Build settings
markdown: kramdown
